{
  "formatVersion": "1.1",
  "component": {
    "group": "com.ghostpass",
    "module": "gopass-kiosk-sdk",
    "version": "1.0.10",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "prodReleaseVariantProdReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "gopass-kiosk-sdk-1.0.10.aar",
          "url": "gopass-kiosk-sdk-1.0.10.aar",
          "size": 44755624,
          "sha512": "96493d6c1cea5738c6e919512eded48a1c5f3264b2707bc737fd031462b7116c4585b19704d7afea20ee4d67c821e6aaff41043e43ee18d62ae8db5b5612030e",
          "sha256": "38ca8e9f00a06b16e1e92f53e321899b26b1fcb8415a2a98f7f75f710e598eac",
          "sha1": "28cca0c759b56f7e40d0657e66100539116e31b3",
          "md5": "25fd88993bcfc7ffb3fad484840b107f"
        }
      ]
    },
    {
      "name": "prodReleaseVariantProdReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.altbeacon",
          "module": "android-beacon-library",
          "version": {
            "requires": "2.20"
          }
        },
        {
          "group": "com.google.android.play",
          "module": "integrity",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp-sse",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-kotlinx-serialization",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-play-services",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation-experimental",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "gopass-kiosk-sdk-1.0.10.aar",
          "url": "gopass-kiosk-sdk-1.0.10.aar",
          "size": 44755624,
          "sha512": "96493d6c1cea5738c6e919512eded48a1c5f3264b2707bc737fd031462b7116c4585b19704d7afea20ee4d67c821e6aaff41043e43ee18d62ae8db5b5612030e",
          "sha256": "38ca8e9f00a06b16e1e92f53e321899b26b1fcb8415a2a98f7f75f710e598eac",
          "sha1": "28cca0c759b56f7e40d0657e66100539116e31b3",
          "md5": "25fd88993bcfc7ffb3fad484840b107f"
        }
      ]
    },
    {
      "name": "prodReleaseVariantProdReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gopass-kiosk-sdk-1.0.10-sources.jar",
          "url": "gopass-kiosk-sdk-1.0.10-sources.jar",
          "size": 102032,
          "sha512": "2418e66d958da9c40b6a49aad133c71798c469dc200c43d760e251d7ba03fb2d869cb8727b481b102b398e714c5599356698460d61253ac1dd17216946cc3c67",
          "sha256": "76d28d3aa2f0df4a36432e172237a257ae4c0e839e52af107b11621b928b8904",
          "sha1": "1e906cdfe55d10dc199349ba7471e0dd9bff5620",
          "md5": "cb57af87998ce415ae6918d821878dc9"
        }
      ]
    }
  ]
}
