{
  "formatVersion": "1.1",
  "component": {
    "group": "com.ghostpass",
    "module": "gopass-kiosk-sdk",
    "version": "1.0.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "prodReleaseVariantProdReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "gopass-kiosk-sdk-1.0.7.aar",
          "url": "gopass-kiosk-sdk-1.0.7.aar",
          "size": 44763698,
          "sha512": "25611d8c70a0b8ca84bfccd5276f6d7f6bf59b624ffb9ab454a6ec0e682c0091d2af2d189c766fa95da56ba92cdf261022a07d63e9771a0be7dc1b4231421e73",
          "sha256": "3526988f30fc001d3a64a8d1ec593a736356f85327e45c9e4848d21314963f18",
          "sha1": "66ec2f7a936dc8db8f0e7ee2c0d48bf2939ab1a1",
          "md5": "7b59aeb35d20c52a60cef68394de5f05"
        }
      ]
    },
    {
      "name": "prodReleaseVariantProdReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.altbeacon",
          "module": "android-beacon-library",
          "version": {
            "requires": "2.20"
          }
        },
        {
          "group": "com.google.android.play",
          "module": "integrity",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp-sse",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-kotlinx-serialization",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-play-services",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation-experimental",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "gopass-kiosk-sdk-1.0.7.aar",
          "url": "gopass-kiosk-sdk-1.0.7.aar",
          "size": 44763698,
          "sha512": "25611d8c70a0b8ca84bfccd5276f6d7f6bf59b624ffb9ab454a6ec0e682c0091d2af2d189c766fa95da56ba92cdf261022a07d63e9771a0be7dc1b4231421e73",
          "sha256": "3526988f30fc001d3a64a8d1ec593a736356f85327e45c9e4848d21314963f18",
          "sha1": "66ec2f7a936dc8db8f0e7ee2c0d48bf2939ab1a1",
          "md5": "7b59aeb35d20c52a60cef68394de5f05"
        }
      ]
    },
    {
      "name": "prodReleaseVariantProdReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gopass-kiosk-sdk-1.0.7-sources.jar",
          "url": "gopass-kiosk-sdk-1.0.7-sources.jar",
          "size": 103161,
          "sha512": "2a092db735f525d62442409284c3221c17c225a0fa1b09cb0043040543733191d6a2824196cc7420f7ff59b8c2a70bd59326c5902be0658629801ec20604d74d",
          "sha256": "6437f58718b02a8d84ba69d216c669d26b85c0988363696e870c777a8b997748",
          "sha1": "4ccec9f268a98e7832e746dabc4a697f0524f9ae",
          "md5": "9e5d92ec330874abf7a35a6aa9305593"
        }
      ]
    }
  ]
}
