{
  "formatVersion": "1.1",
  "component": {
    "group": "com.ghostpass",
    "module": "gopass-kiosk-sdk",
    "version": "1.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "prodReleaseVariantProdReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "gopass-kiosk-sdk-1.0.1.aar",
          "url": "gopass-kiosk-sdk-1.0.1.aar",
          "size": 44723590,
          "sha512": "b5e134e166cc1abbb33d1127a546f916d880d261a518439c7c7905bfb741467e5989d621ebcf90ca1212f031fef19c7155309067e9fe1de643d4ebb3403fddb6",
          "sha256": "94d0b4009afeef13a5034f0f04bc0e6e3efbcded5ee71ce889fecc372a2f4176",
          "sha1": "78ce205741ce6fb8a566d78049e756a70900ed77",
          "md5": "9b644a716af7fc9bfcf52d702c2e7d6b"
        }
      ]
    },
    {
      "name": "prodReleaseVariantProdReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.altbeacon",
          "module": "android-beacon-library",
          "version": {
            "requires": "2.20"
          }
        },
        {
          "group": "com.google.android.play",
          "module": "integrity",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp-sse",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-kotlinx-serialization",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-play-services",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation-experimental",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "gopass-kiosk-sdk-1.0.1.aar",
          "url": "gopass-kiosk-sdk-1.0.1.aar",
          "size": 44723590,
          "sha512": "b5e134e166cc1abbb33d1127a546f916d880d261a518439c7c7905bfb741467e5989d621ebcf90ca1212f031fef19c7155309067e9fe1de643d4ebb3403fddb6",
          "sha256": "94d0b4009afeef13a5034f0f04bc0e6e3efbcded5ee71ce889fecc372a2f4176",
          "sha1": "78ce205741ce6fb8a566d78049e756a70900ed77",
          "md5": "9b644a716af7fc9bfcf52d702c2e7d6b"
        }
      ]
    },
    {
      "name": "prodReleaseVariantProdReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gopass-kiosk-sdk-1.0.1-sources.jar",
          "url": "gopass-kiosk-sdk-1.0.1-sources.jar",
          "size": 96994,
          "sha512": "10de3e692cadf9223239f95cc91454ecdd6b94b119ef74805dd159a31987f19dfcd0eacfe645aa94516d977ca09dc29b6484e7b223dd4d7da373f3b939f9d845",
          "sha256": "8be12acf5dcd2270d38f7f419be42f945d9230b5dfc19a03432815916db79716",
          "sha1": "cde9edd8740fa2be16a59ae1cea3ad30418927e8",
          "md5": "ce6c75da672bf8fa8da68cbf37674733"
        }
      ]
    }
  ]
}
