{
  "formatVersion": "1.1",
  "component": {
    "group": "com.ghostpass",
    "module": "gopass-user-sdk",
    "version": "1.0.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "prodReleaseVariantProdReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "gopass-user-sdk-1.0.8.aar",
          "url": "gopass-user-sdk-1.0.8.aar",
          "size": 44813045,
          "sha512": "53740def852d193111cd7fb7da58ae0a6e18ddb5d728448b2f19dc9d644410799e1b118ddd887bfb2b3fd000e89b987563731f3599fa4896e044869193d66380",
          "sha256": "756a4dff48e1ef628db5c9e11c2f07fcb92774b9925c546efc944684238c2de1",
          "sha1": "c83631a35c86952815bd438c3f79702391923e65",
          "md5": "8f3bd76de2307e8ab1a3324acfaddf92"
        }
      ]
    },
    {
      "name": "prodReleaseVariantProdReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "com.google.android.play",
          "module": "integrity",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-play-services",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp-sse",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-kotlinx-serialization",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.15.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "gopass-user-sdk-1.0.8.aar",
          "url": "gopass-user-sdk-1.0.8.aar",
          "size": 44813045,
          "sha512": "53740def852d193111cd7fb7da58ae0a6e18ddb5d728448b2f19dc9d644410799e1b118ddd887bfb2b3fd000e89b987563731f3599fa4896e044869193d66380",
          "sha256": "756a4dff48e1ef628db5c9e11c2f07fcb92774b9925c546efc944684238c2de1",
          "sha1": "c83631a35c86952815bd438c3f79702391923e65",
          "md5": "8f3bd76de2307e8ab1a3324acfaddf92"
        }
      ]
    },
    {
      "name": "prodReleaseVariantProdReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gopass-user-sdk-1.0.8-sources.jar",
          "url": "gopass-user-sdk-1.0.8-sources.jar",
          "size": 127639,
          "sha512": "d599cf4236c9eb04cb7e4b8985b2fe547d81036d6359954ca7ac4b92eb82a593a7e56c12e907a4ea90687f933e80ff65f08517723c5b38018beb83b604be973a",
          "sha256": "1a8d10e991ada9181ba06f3e1e9b1303b2b1f41155b9811f838682970bb58532",
          "sha1": "4fa846a5ef495413880ddb1411a2484e5dcd6036",
          "md5": "e3ae827d906a7dfbd815d24226eda988"
        }
      ]
    }
  ]
}
