{
  "formatVersion": "1.1",
  "component": {
    "group": "com.ghostpass",
    "module": "gopass-kiosk-sdk",
    "version": "1.0.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "prodReleaseVariantProdReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "gopass-kiosk-sdk-1.0.4.aar",
          "url": "gopass-kiosk-sdk-1.0.4.aar",
          "size": 44739174,
          "sha512": "323ad6e8e592d732552d65810330310249fd73619a98af7f493ed136aa80b5fcb28de3ad554f0b6856df30720f944c41ea38a2b4b8b26df96a06e70142a0d742",
          "sha256": "52c9cde7de315b98f11f563b73c83be21f3f53c387595784e2060aee0b0a0cf2",
          "sha1": "fab8b092fe838afb02a38bc98327e115e458c0e4",
          "md5": "16f7b7c414c2cb5dc824e2f299d0cb98"
        }
      ]
    },
    {
      "name": "prodReleaseVariantProdReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.altbeacon",
          "module": "android-beacon-library",
          "version": {
            "requires": "2.20"
          }
        },
        {
          "group": "com.google.android.play",
          "module": "integrity",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp-sse",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-kotlinx-serialization",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-play-services",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation-experimental",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "gopass-kiosk-sdk-1.0.4.aar",
          "url": "gopass-kiosk-sdk-1.0.4.aar",
          "size": 44739174,
          "sha512": "323ad6e8e592d732552d65810330310249fd73619a98af7f493ed136aa80b5fcb28de3ad554f0b6856df30720f944c41ea38a2b4b8b26df96a06e70142a0d742",
          "sha256": "52c9cde7de315b98f11f563b73c83be21f3f53c387595784e2060aee0b0a0cf2",
          "sha1": "fab8b092fe838afb02a38bc98327e115e458c0e4",
          "md5": "16f7b7c414c2cb5dc824e2f299d0cb98"
        }
      ]
    },
    {
      "name": "prodReleaseVariantProdReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gopass-kiosk-sdk-1.0.4-sources.jar",
          "url": "gopass-kiosk-sdk-1.0.4-sources.jar",
          "size": 98846,
          "sha512": "006e2abb2c99dc249f57ff03705eb33a388ea6df2e17025ec892b725fdcafe6a00c2430afcd265cafc531055fe20fa9584c320c384ba4983e8b1a13687edae54",
          "sha256": "199f0adefad76a6b802d41ba007b5698bf4e2fa284586790f761cd26d4113766",
          "sha1": "f9c7d841a83a04e4d76e1975969dfa5bb22ff6e9",
          "md5": "5239759abb396f000b197b503ccd26e0"
        }
      ]
    }
  ]
}
