{
  "formatVersion": "1.1",
  "component": {
    "group": "com.ghostpass",
    "module": "gopass-user-sdk",
    "version": "1.0.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "prodReleaseVariantProdReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "gopass-user-sdk-1.0.4.aar",
          "url": "gopass-user-sdk-1.0.4.aar",
          "size": 44792366,
          "sha512": "48b8b32bd6a950babd5c335deb7f8cfa8a65cc5a3ade54abb00b18373945ea8c09620b075cfc17ec55180b02735c92fd9e2b4fcb1c203f4a78fbc733a9318b6a",
          "sha256": "b2bd1c574da9d6e932a0691ce0aced70d9732007f06e41ff7878dfa8b89b3b19",
          "sha1": "550f7fae9736ded82c13d22936023b0eacbd2513",
          "md5": "80bceef15fde944f177843010d5a6c15"
        }
      ]
    },
    {
      "name": "prodReleaseVariantProdReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "com.google.android.play",
          "module": "integrity",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-play-services",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp-sse",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-kotlinx-serialization",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.15.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "gopass-user-sdk-1.0.4.aar",
          "url": "gopass-user-sdk-1.0.4.aar",
          "size": 44792366,
          "sha512": "48b8b32bd6a950babd5c335deb7f8cfa8a65cc5a3ade54abb00b18373945ea8c09620b075cfc17ec55180b02735c92fd9e2b4fcb1c203f4a78fbc733a9318b6a",
          "sha256": "b2bd1c574da9d6e932a0691ce0aced70d9732007f06e41ff7878dfa8b89b3b19",
          "sha1": "550f7fae9736ded82c13d22936023b0eacbd2513",
          "md5": "80bceef15fde944f177843010d5a6c15"
        }
      ]
    },
    {
      "name": "prodReleaseVariantProdReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gopass-user-sdk-1.0.4-sources.jar",
          "url": "gopass-user-sdk-1.0.4-sources.jar",
          "size": 121272,
          "sha512": "ca8a32af85e3c97bb2bcba02a7dcb604116d76d1037615c4dc39738fdf592bc2803e5f3bcc7074cfaeb52ffcad3fafb6e33fcb6d99f4890e49cc9548b7561313",
          "sha256": "d511cecb19221b3a9779d2a2060842a9b9f03d06cc7fdbc862c4d9fda4ca74ec",
          "sha1": "db113248050fa3c209f95bf81b8b6d779bfd203a",
          "md5": "3439129afd7a389f4c8aa13d516e08eb"
        }
      ]
    }
  ]
}
