{
  "formatVersion": "1.1",
  "component": {
    "group": "com.ghostpass",
    "module": "gopass-kiosk-sdk",
    "version": "1.0.11",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "prodReleaseVariantProdReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "gopass-kiosk-sdk-1.0.11.aar",
          "url": "gopass-kiosk-sdk-1.0.11.aar",
          "size": 44789771,
          "sha512": "697394bf46fd771d4d58670467d69a4f294f1320f887253723290cec37af4be2f84349e22a3ecf8efb213926802af1b7c77e098eb7cf2d03ffb765bc2a507160",
          "sha256": "c8f69613f773dddb71ab15c421c5cc1488e9606d96621ae898f6cafc87c5df12",
          "sha1": "1c251e92f6a024d57133051f426f59ca74826a94",
          "md5": "70d1038c7c364319d1d39f4262762a84"
        }
      ]
    },
    {
      "name": "prodReleaseVariantProdReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.altbeacon",
          "module": "android-beacon-library",
          "version": {
            "requires": "2.20"
          }
        },
        {
          "group": "com.google.android.play",
          "module": "integrity",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp-sse",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-kotlinx-serialization",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-play-services",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation-experimental",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "gopass-kiosk-sdk-1.0.11.aar",
          "url": "gopass-kiosk-sdk-1.0.11.aar",
          "size": 44789771,
          "sha512": "697394bf46fd771d4d58670467d69a4f294f1320f887253723290cec37af4be2f84349e22a3ecf8efb213926802af1b7c77e098eb7cf2d03ffb765bc2a507160",
          "sha256": "c8f69613f773dddb71ab15c421c5cc1488e9606d96621ae898f6cafc87c5df12",
          "sha1": "1c251e92f6a024d57133051f426f59ca74826a94",
          "md5": "70d1038c7c364319d1d39f4262762a84"
        }
      ]
    },
    {
      "name": "prodReleaseVariantProdReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gopass-kiosk-sdk-1.0.11-sources.jar",
          "url": "gopass-kiosk-sdk-1.0.11-sources.jar",
          "size": 110316,
          "sha512": "6515ba505fad09c3a0648903e4377d588b19c41a5dd4af206ceb8c4a2652bf130eef103b6dc430d9e631742d039da38f92d116e5c32f5755fe7a480280a6cfcb",
          "sha256": "85932d8369ccc1e482959da1f87da8063a555cdb42805c7d0d7bda70c4b6026b",
          "sha1": "acbd08f0b1dd1a34e8bd7fbfe3b726ab68a169bf",
          "md5": "bdd5e0613129d114f9551ce56ab7efbb"
        }
      ]
    }
  ]
}
